/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PruebaProyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author XPC
 */
public class EliminarAnimal extends javax.swing.JFrame {

    /**
     * Creates new form EliminarAnimal
     */
    public EliminarAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AtrasEAL = new javax.swing.JButton();
        MenuEliAni = new javax.swing.JButton();
        GuardarEliAni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numANI = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(119, 139, 81));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        AtrasEAL.setText("Atras");
        AtrasEAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasEALActionPerformed(evt);
            }
        });

        MenuEliAni.setText("Menu");
        MenuEliAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEliAniActionPerformed(evt);
            }
        });

        GuardarEliAni.setText("Guardar");
        GuardarEliAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarEliAniActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese el numero del ani que  desea eliminar");

        numANI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numANIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(GuardarEliAni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AtrasEAL)
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(697, 697, 697)
                        .addComponent(MenuEliAni))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(553, 553, 553)
                        .addComponent(numANI, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(562, 562, 562)
                        .addComponent(jLabel1)))
                .addContainerGap(625, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(numANI, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 367, Short.MAX_VALUE)
                .addComponent(MenuEliAni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtrasEAL)
                    .addComponent(GuardarEliAni))
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasEALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasEALActionPerformed
        RegistroDeAnimales atrasEAL = new RegistroDeAnimales();
        atrasEAL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasEALActionPerformed

    private void MenuEliAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEliAniActionPerformed
        Menu Menu1 = new Menu();
        Menu1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuEliAniActionPerformed

    private void GuardarEliAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarEliAniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarEliAniActionPerformed

    private void numANIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numANIActionPerformed
        int numani = Integer.parseInt(numANI.getText());
        Home elimANI = new Home();
        
        for (int i = 0; i < elimANI.arrAnimales.length; i++) {
            if (numani==elimANI.arrAnimales[i].getAni()) {
                String nombre= "";
                elimANI.arrAnimales[i].setNombre(nombre);
                
                int edad= 0;
                elimANI.arrAnimales[i].setEdad(edad);
                
                String especie= "";
                elimANI.arrAnimales[i].setEspecie(especie);
                
                int habitat= 0;
                elimANI.arrAnimales[i].setHabitat(habitat);
                
                int ani= 0;
                elimANI.arrAnimales[i].setAni(ani);
                
                String alimento= "";
                elimANI.arrAnimales[i].setAlimento(alimento);
                
                int horario= 0;
                elimANI.arrAnimales[i].setHorario(horario);
                
                int frecuencia= 0;
                elimANI.arrAnimales[i].setFrecuencia(frecuencia);
            }
        }
        JOptionPane.showMessageDialog(null, "Animal eliminado con exito");
    }//GEN-LAST:event_numANIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasEAL;
    private javax.swing.JButton GuardarEliAni;
    private javax.swing.JButton MenuEliAni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numANI;
    // End of variables declaration//GEN-END:variables
}
