/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PruebaProyecto;

//import PruebaProyecto.RegistroDeAnimales;

import javax.swing.JOptionPane;


/**
 *
 * @author XPC
 */
public class ModificarAnimalLobby extends javax.swing.JFrame {

    /**
     * Creates new form ModificarAnimal
     */
    public ModificarAnimalLobby() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        AtrasMAL = new javax.swing.JButton();
        MenuModAni = new javax.swing.JButton();
        GuardarModAni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SoliNumAni = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(119, 139, 81));

        AtrasMAL.setText("Atras");
        AtrasMAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasMALActionPerformed(evt);
            }
        });

        MenuModAni.setText("Menu");
        MenuModAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuModAniActionPerformed(evt);
            }
        });

        GuardarModAni.setText("Guardar");
        GuardarModAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarModAniActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese el numero de ani ");

        SoliNumAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoliNumAniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(GuardarModAni)
                .addGap(439, 439, 439)
                .addComponent(MenuModAni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 564, Short.MAX_VALUE)
                .addComponent(AtrasMAL)
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(531, 531, 531)
                        .addComponent(SoliNumAni, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(570, 570, 570)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addComponent(SoliNumAni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtrasMAL)
                    .addComponent(GuardarModAni)
                    .addComponent(MenuModAni))
                .addGap(153, 153, 153))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasMALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasMALActionPerformed
        RegistroDeAnimales atrasMAL = new RegistroDeAnimales();
        atrasMAL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasMALActionPerformed

    private void MenuModAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuModAniActionPerformed
        Menu menu1 = new Menu();
        menu1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuModAniActionPerformed

    private void GuardarModAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarModAniActionPerformed

    }//GEN-LAST:event_GuardarModAniActionPerformed

    private void SoliNumAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoliNumAniActionPerformed
        int numAni = Integer.parseInt(SoliNumAni.getText());
        
        Home modificacion = new Home();
        
        for (int i = 0; i < modificacion.arrAnimales.length; i++) {
            if (numAni== modificacion.arrAnimales[i].getAni()) {
                String nombre= JOptionPane.showInputDialog("Ingrese el nombre del nuevo animal: ");
                modificacion.arrAnimales[i].setNombre(nombre);
                
                int edad= Integer.parseInt(JOptionPane.showInputDialog("Ingrese la edad del nuevo animal: "));
                modificacion.arrAnimales[i].setEdad(edad);
                
                String especie= JOptionPane.showInputDialog("Ingrese la especie del nuevo animal: ");
                modificacion.arrAnimales[i].setEspecie(especie);
                
                int habitat= Integer.parseInt(JOptionPane.showInputDialog("Ingrese el habitad del animal nuevo: "));
                modificacion.arrAnimales[i].setHabitat(habitat);
                
                int ani= Integer.parseInt(JOptionPane.showInputDialog("Ingrese el ANI del animal nuevo: "));
                modificacion.arrAnimales[i].setAni(ani);
                
                String alimento= JOptionPane.showInputDialog("Ingrese el alimento del nuevo animal: ");
                modificacion.arrAnimales[i].setAlimento(alimento);
                
                int horario= Integer.parseInt(JOptionPane.showInputDialog("Ingrese el horario del nuevo animal: "));
                modificacion.arrAnimales[i].setHorario(horario);
                
                int frecuencia= Integer.parseInt(JOptionPane.showInputDialog("Ingrese el nuevo nombre de animal: "));
                modificacion.arrAnimales[i].setFrecuencia(frecuencia);
            }
        }
        JOptionPane.showMessageDialog(null, "Correciones hechas");
        
    }//GEN-LAST:event_SoliNumAniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarAnimalLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarAnimalLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarAnimalLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarAnimalLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarAnimalLobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasMAL;
    private javax.swing.JButton GuardarModAni;
    private javax.swing.JButton MenuModAni;
    private javax.swing.JTextField SoliNumAni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
